#Buttons
set_property PACKAGE_PIN U18 [get_ports clk]						
	set_property IOSTANDARD LVCMOS33 [get_ports clk]

# LEDs
set_property PACKAGE_PIN U16 [get_ports lights[0]]					
	set_property IOSTANDARD LVCMOS33 [get_ports lights[0]]
set_property PACKAGE_PIN E19 [get_ports lights[1]]					
	set_property IOSTANDARD LVCMOS33 [get_ports lights[1]]
set_property PACKAGE_PIN U19 [get_ports lights[2]]					
	set_property IOSTANDARD LVCMOS33 [get_ports lights[2]]
set_property PACKAGE_PIN V19 [get_ports lights[3]]					
	set_property IOSTANDARD LVCMOS33 [get_ports lights[3]]
set_property PACKAGE_PIN W18 [get_ports lights[4]]					
	set_property IOSTANDARD LVCMOS33 [get_ports lights[4]]
set_property PACKAGE_PIN U15 [get_ports lights[5]]					
	set_property IOSTANDARD LVCMOS33 [get_ports lights[5]]
set_property PACKAGE_PIN U14 [get_ports lights[6]]					
	set_property IOSTANDARD LVCMOS33 [get_ports lights[6]]
set_property PACKAGE_PIN V14 [get_ports lights[7]]					
	set_property IOSTANDARD LVCMOS33 [get_ports lights[7]]
set_property PACKAGE_PIN V13 [get_ports lights[8]]					
	set_property IOSTANDARD LVCMOS33 [get_ports lights[8]]
set_property PACKAGE_PIN V3 [get_ports lights[9]]					
	set_property IOSTANDARD LVCMOS33 [get_ports lights[9]]
set_property PACKAGE_PIN W3 [get_ports lights[10]]					
	set_property IOSTANDARD LVCMOS33 [get_ports lights[10]]
set_property PACKAGE_PIN U3 [get_ports lights[11]]					
	set_property IOSTANDARD LVCMOS33 [get_ports lights[11]]
	
# Switches
set_property PACKAGE_PIN V17 [get_ports V]					
	set_property IOSTANDARD LVCMOS33 [get_ports V]
set_property PACKAGE_PIN V16 [get_ports Z]					
	set_property IOSTANDARD LVCMOS33 [get_ports Z]
	
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]